/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/intro`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/status` | `/status`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `/friends`; params?: Router.UnknownInputParams; } | { pathname: `/friends/requests`; params?: Router.UnknownInputParams; } | { pathname: `/meetings/create`; params?: Router.UnknownInputParams; } | { pathname: `/meetings`; params?: Router.UnknownInputParams; } | { pathname: `/status/create`; params?: Router.UnknownInputParams; } | { pathname: `/status/view`; params?: Router.UnknownInputParams; } | { pathname: `/chats/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/meetings/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/intro`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/status` | `/status`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/contacts`; params?: Router.UnknownOutputParams; } | { pathname: `/friends`; params?: Router.UnknownOutputParams; } | { pathname: `/friends/requests`; params?: Router.UnknownOutputParams; } | { pathname: `/meetings/create`; params?: Router.UnknownOutputParams; } | { pathname: `/meetings`; params?: Router.UnknownOutputParams; } | { pathname: `/status/create`; params?: Router.UnknownOutputParams; } | { pathname: `/status/view`; params?: Router.UnknownOutputParams; } | { pathname: `/chats/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/meetings/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/user/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/intro${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/maps${`?${string}` | `#${string}` | ''}` | `/maps${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/status${`?${string}` | `#${string}` | ''}` | `/status${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/contacts${`?${string}` | `#${string}` | ''}` | `/friends${`?${string}` | `#${string}` | ''}` | `/friends/requests${`?${string}` | `#${string}` | ''}` | `/meetings/create${`?${string}` | `#${string}` | ''}` | `/meetings${`?${string}` | `#${string}` | ''}` | `/status/create${`?${string}` | `#${string}` | ''}` | `/status/view${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/intro`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/status` | `/status`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `/friends`; params?: Router.UnknownInputParams; } | { pathname: `/friends/requests`; params?: Router.UnknownInputParams; } | { pathname: `/meetings/create`; params?: Router.UnknownInputParams; } | { pathname: `/meetings`; params?: Router.UnknownInputParams; } | { pathname: `/status/create`; params?: Router.UnknownInputParams; } | { pathname: `/status/view`; params?: Router.UnknownInputParams; } | `/chats/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/meetings/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/user/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/chats/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/meetings/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
